version: '3'
services:
  postgres_db:
    image: fiitteam8/postgres_db:latest
    container_name: postgres_db
    env_file:
      - ../backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  node_server:
    build: 
      context: ../backend/.
    container_name: node_server
    env_file:
      - ../backend/.env
    ports:
      - 8080:8080
    
  react_frontend:
    build: 
      context: ../frontend/.
    container_name: react_frontend
    env_file:
      - ../frontend/.env
    ports:
      - 3000:80

volumes:
  postgres_data:
